# Real Remote Desktop Agent Configuration

[server]
host = "0.0.0.0"
port = 8080
max_connections = 10
connection_timeout = 300
heartbeat_interval = 30

[auth]
token = null  # Set to a secure token for production
require_auth = true
session_timeout = 3600
max_failed_attempts = 5

[capture]
video = true
audio = false
quality = "high"
framerate = 30
codec = "h264"
hardware_acceleration = true
multi_monitor = true
capture_cursor = true

[input]
enable_mouse = true
enable_keyboard = true
enable_touch = true
enable_clipboard = true
enable_file_transfer = true
mouse_sensitivity = 1.0
keyboard_repeat_delay = 500

[transport]
webrtc_enabled = true
websocket_enabled = true
ice_servers = [
    "stun:stun.l.google.com:19302",
    "stun:stun1.l.google.com:19302"
]
max_bitrate = 5000000
enable_compression = true

[security]
enable_encryption = true
enable_audit_logging = true
allowed_ips = []
rate_limit_requests = 100
rate_limit_window = 60

[logging]
level = "info"
file = "logs/agent.log"
max_file_size = 10485760  # 10MB
max_files = 5
enable_console = true 